export const repositoryContansts = {
  GET_REPOSITORY_REQUEST: 'app/repository/GET_REPOSITORY_REQUEST',
  GET_REPOSITORY_SUCESS: 'app/repository/GET_REPOSITORY_SUCESS',
  GET_REPOSITORY_FAILURE: 'app/repository/GET_REPOSITORY_FAILURE',
  SHARE_LINKEDIN_REQUEST: 'app/repository/SHARE_LINKEDIN_REQUEST',
  SHARE_LINKEDIN_SUCESS: 'app/repository/SHARE_LINKEDIN_SUCESS',
  SHARE_LINKEDIN_FAILURE: 'app/repository/SHARE_LINKEDIN_FAILURE',
};
